#!/usr/bin/env python3
"""Upload the generated textures and sounds to Roblox, and write their ids back into the config.

The 16 PNGs in assets/textures/ and the 55 WAVs in assets/audio/ are generated by tools/ and committed.
Roblox only renders or plays them once they are uploaded to an account and referenced by id, which used
to be 71 manual uploads and 71 copy-pastes (docs/STUDIO_SETUP.md sections 7 and 8). This does it through
the Open Cloud Assets API instead:

    python3 scripts/upload_assets.py quota     # read-only: how many audio uploads are left this month
    python3 scripts/upload_assets.py plan      # no network: what would be uploaded
    python3 scripts/upload_assets.py upload    # upload what is missing, then rewrite the config blocks
    python3 scripts/upload_assets.py upload --reupload   # also files regenerated since their upload
    python3 scripts/upload_assets.py status    # re-read moderation: nothing shows in game until Approved

Why it is careful:
  * An upload is not free. Audio has a monthly quota (10 without ID verification, 100 with, per the
    Open Cloud guide), and neither audio nor images can be updated in place: every upload makes a new
    asset and spends a slot. So assets/roblox-assets.lock.json records what was uploaded with the file's
    SHA-256, and a file whose bytes have not changed is never uploaded twice.
  * expectedPrice is sent as 0, so an upload that would cost Robux fails instead of charging.
  * The key is read from the environment or from .env.local (gitignored) and is never printed.

The ids land in one generated block per config module (between "-- BEGIN UPLOADED" and
"-- END UPLOADED"), which keeps those modules pure data; tests/UploadedAssets.spec.luau holds the blocks
to the lock file and the lock file to the bytes on disk.

Standard library only, like the generators in tools/.
"""

from __future__ import annotations

import datetime
import hashlib
import json
import os
import pathlib
import sys
import time
import urllib.error
import urllib.request
import uuid

ROOT = pathlib.Path(__file__).resolve().parent.parent
LOCK = ROOT / "assets" / "roblox-assets.lock.json"
ENV_FILE = ROOT / ".env.local"
KEY_NAMES = ("ROBLOX_API_KEY", "ASPHALT_API_KEY")

API = "https://apis.roblox.com"
USER_AGENT = "vellum-upload-assets/1.0"
POLL_SECONDS = 1.5
POLL_ATTEMPTS = 40
# Between two creates. The documented limit is 120 per minute per key owner; this stays far below it.
CREATE_SPACING_SECONDS = 0.6

# Which files go where, and as what. Each target is the config module whose block receives the ids.
KINDS = {
    "texture": {
        "dir": ROOT / "assets" / "textures",
        "glob": "*.png",
        "asset_type": "Image",
        "content_type": "image/png",
        "target": ROOT / "src" / "shared" / "Config" / "AssetIds.luau",
        "quota_type": "DECAL",
    },
    "animation": {
        "dir": ROOT / "assets" / "animations",
        "glob": "*.rbxmx",
        # The content type the Assets API documents for both .rbxm and .rbxmx.
        "asset_type": "Animation",
        "content_type": "model/x-rbxm",
        "target": ROOT / "src" / "shared" / "Config" / "AnimationConfig.luau",
        "quota_type": "ANIMATION",
    },
    "sound": {
        "dir": ROOT / "assets" / "audio",
        "glob": "*.wav",
        "asset_type": "Audio",
        "content_type": "audio/wav",
        "target": ROOT / "src" / "shared" / "Config" / "SoundConfig.luau",
        "quota_type": "AUDIO",
    },
    # The generated volumes (D-114). Open Cloud takes a mesh only as a Model, which the importer turns
    # into a MeshPart; the id a SpecialMesh renders is that MeshPart's, read in Studio and written back
    # with `record-meshes`. Until then the block leaves the mesh out and the renderer skips it.
    "mesh": {
        "dir": ROOT / "assets" / "meshes",
        "glob": "*.glb",
        "asset_type": "Model",
        "content_type": "model/gltf-binary",
        "target": ROOT / "src" / "shared" / "Config" / "MeshConfig.luau",
        "quota_type": "MODEL",
    },
}

BEGIN = "-- BEGIN UPLOADED"
END = "-- END UPLOADED"


class ApiError(RuntimeError):
    pass


def read_key() -> str:
    for name in KEY_NAMES:
        value = os.environ.get(name)
        if value:
            return value.strip()
    if ENV_FILE.exists():
        for line in ENV_FILE.read_text().splitlines():
            name, _, value = line.partition("=")
            if name.strip() in KEY_NAMES and value.strip():
                return value.strip()
    sys.exit(f"no API key: set one of {', '.join(KEY_NAMES)} in the environment or in .env.local")


def load_lock() -> dict:
    if LOCK.exists():
        return json.loads(LOCK.read_text())
    return {"creator": {}, "assets": {}}


def save_lock(lock: dict) -> None:
    lock["assets"] = dict(sorted(lock["assets"].items()))
    LOCK.write_text(json.dumps(lock, indent=2, ensure_ascii=False) + "\n")


def sha256(path: pathlib.Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def rel(path: pathlib.Path) -> str:
    return path.relative_to(ROOT).as_posix()


def files() -> list[tuple[str, pathlib.Path]]:
    out = []
    for kind, spec in KINDS.items():
        for path in sorted(spec["dir"].glob(spec["glob"])):
            out.append((kind, path))
    return out


def request(method: str, url: str, key: str, body: bytes | None = None, content_type: str | None = None) -> dict:
    # A User-Agent naming this script rather than urllib's generic default: requests from this machine
    # have drawn HTTP 403 "WAF Blocked Request" from Roblox's web firewall, and a script should say what
    # it is anyway.
    headers = {"x-api-key": key, "User-Agent": USER_AGENT}
    if content_type:
        headers["Content-Type"] = content_type
    for attempt in range(6):
        req = urllib.request.Request(url, data=body, method=method, headers=headers)
        try:
            with urllib.request.urlopen(req, timeout=60) as response:
                text = response.read().decode()
                return json.loads(text) if text else {}
        except urllib.error.HTTPError as error:
            detail = error.read().decode(errors="replace")
            if error.code == 429 and attempt < 5:
                wait = float(error.headers.get("retry-after") or 2 ** attempt)
                print(f"  rate limited, waiting {wait:.0f} s")
                time.sleep(wait)
                continue
            raise ApiError(f"{method} {url} -> HTTP {error.code}: {detail[:500]}") from None
    raise ApiError(f"{method} {url} -> still rate limited after retries")


def multipart(fields: dict[str, tuple[str | None, str, bytes]]) -> tuple[bytes, str]:
    boundary = uuid.uuid4().hex
    parts = []
    for name, (filename, content_type, data) in fields.items():
        disposition = f'form-data; name="{name}"'
        if filename:
            disposition += f'; filename="{filename}"'
        parts.append(
            f"--{boundary}\r\nContent-Disposition: {disposition}\r\nContent-Type: {content_type}\r\n\r\n".encode()
            + data
            + b"\r\n"
        )
    return b"".join(parts) + f"--{boundary}--\r\n".encode(), f"multipart/form-data; boundary={boundary}"


def quota(key: str, user_id: str, asset_type: str) -> dict | None:
    # Unfiltered, then filtered here. The endpoint documents a CEL filter
    # ("quotaType == RateLimitUpload && assetType == Audio"), but that query string, with its && and ==,
    # drew HTTP 403 "WAF Blocked Request" from Roblox's web firewall where the same call without it
    # reached the API.
    data = request("GET", f"{API}/cloud/v2/users/{user_id}/asset-quotas?maxPageSize=100", key)
    # The response spells the enums in capitals ("RATE_LIMIT_UPLOAD", "AUDIO"), not the way the filter
    # documentation does ("RateLimitUpload", "Audio"), and omits "usage" while nothing has been used.
    for entry in data.get("assetQuotas") or []:
        if entry.get("quotaType") == "RATE_LIMIT_UPLOAD" and entry.get("assetType") == asset_type:
            return entry
    return None


def upload_one(key: str, user_id: str, kind: str, path: pathlib.Path) -> dict:
    spec = KINDS[kind]
    meta = {
        "assetType": spec["asset_type"],
        "displayName": f"Vellum {path.stem}",
        "description": f"Vellum, generated by tools/ ({rel(path)}).",
        "creationContext": {"creator": {"userId": user_id}, "expectedPrice": 0},
    }
    body, content_type = multipart(
        {
            "request": (None, "application/json", json.dumps(meta).encode()),
            "fileContent": (path.name, spec["content_type"], path.read_bytes()),
        }
    )
    operation = request("POST", f"{API}/assets/v1/assets", key, body, content_type)
    op_path = operation.get("path")
    if not op_path:
        raise ApiError(f"no operation returned for {rel(path)}: {operation}")
    for _ in range(POLL_ATTEMPTS):
        state = request("GET", f"{API}/assets/v1/{op_path}", key)
        if state.get("done"):
            if "response" in state:
                return state["response"]
            raise ApiError(f"upload of {rel(path)} failed: {state.get('error') or state}")
        time.sleep(POLL_SECONDS)
    raise ApiError(f"upload of {rel(path)} did not finish in {POLL_ATTEMPTS * POLL_SECONDS:.0f} s ({op_path})")


def lua_number(value: float) -> str:
    text = f"{value:.4f}".rstrip("0").rstrip(".")
    return "0" if text in ("-0", "") else text


def block_lines(kind: str, prefix: str, lock: dict) -> list[str]:
    """The generated block of one kind. A mesh names the id of the MeshPart the import made and the size
    the importer gave it; a mesh uploaded but not resolved yet is left out, and the renderer skips it."""
    records = sorted((source, record) for source, record in lock["assets"].items() if source.startswith(prefix))
    if kind == "mesh":
        lines = [BEGIN, "local UPLOADED: { [string]: Uploaded } = {"]
        for source, record in records:
            if record.get("meshId") and record.get("native"):
                native = ", ".join(lua_number(v) for v in record["native"])
                lines.append(f'\t["{source}"] = {{ Id = "rbxassetid://{record["meshId"]}", Native = {{ {native} }} }},')
        return lines
    lines = [BEGIN, "local UPLOADED: { [string]: string } = {"]
    for source, record in records:
        lines.append(f'\t["{source}"] = "rbxassetid://{record["assetId"]}",')
    return lines


def write_blocks(lock: dict) -> None:
    for kind, spec in KINDS.items():
        target: pathlib.Path = spec["target"]
        prefix = rel(spec["dir"]) + "/"
        lines = block_lines(kind, prefix, lock)
        entries = lines[2:]
        lines.append("}")
        lines.append(END)
        text = target.read_text()
        start = text.index(BEGIN)
        end = text.index(END, start) + len(END)
        target.write_text(text[:start] + "\n".join(lines) + text[end:])
        print(f"  {rel(target)}: {len(entries)} id(s)")


def plan(lock: dict, reupload: bool = False) -> list[tuple[str, pathlib.Path]]:
    """What needs uploading: files never uploaded, and -- only with reupload -- files whose bytes changed
    since. A changed file cannot be updated in place (Open Cloud refuses updates for audio and images),
    so re-uploading it creates a new asset and spends a quota slot; that is why it takes a flag."""
    todo = []
    for kind, path in files():
        record = lock["assets"].get(rel(path))
        if record is None:
            todo.append((kind, path))
        elif record.get("sha256") != sha256(path):
            if reupload:
                todo.append((kind, path))
            else:
                print(f"  CHANGED since upload (re-upload with --reupload, spends a slot): {rel(path)}")
    return todo


def main(argv: list[str]) -> int:
    # Line by line even into a file or a pipe: an upload run takes minutes and is followed as it goes.
    sys.stdout.reconfigure(line_buffering=True)
    command = argv[1] if len(argv) > 1 else "plan"
    lock = load_lock()
    user_id = os.environ.get("ROBLOX_USER_ID") or lock["creator"].get("userId")

    if command == "plan":
        todo = plan(lock)
        for kind, path in todo:
            print(f"  {kind:7s} {rel(path)}")
        counts = {kind: sum(1 for k, _ in todo if k == kind) for kind in KINDS}
        print(f"{len(todo)} to upload (" + ", ".join(f"{n} {kind}" for kind, n in counts.items()) + ")")
        return 0

    if command == "resolve-snippet":
        # The Luau to paste in Studio's command bar (or run through the Studio MCP) after an upload: it
        # loads each uploaded mesh Model and prints, as JSON, the MeshPart's MeshId and MeshSize that
        # `record-meshes` writes back. Studio, because the key has no right to download an asset.
        models = {
            source: record["assetId"]
            for source, record in sorted(lock["assets"].items())
            if source.startswith(rel(KINDS["mesh"]["dir"]) + "/")
        }
        rows = ",\n".join(f'\t["{source}"] = {asset_id}' for source, asset_id in models.items())
        print(
            "local InsertService = game:GetService(\"InsertService\")\n"
            "local HttpService = game:GetService(\"HttpService\")\n"
            f"local models = {{\n{rows},\n}}\n"
            "local out = {}\n"
            "for source, id in pairs(models) do\n"
            "\tlocal model = InsertService:LoadAsset(id)\n"
            "\tlocal part = model:FindFirstChildWhichIsA(\"MeshPart\", true)\n"
            "\ttable.insert(out, { source = source, assetId = id, meshId = part.MeshId, native = { part.MeshSize.X, part.MeshSize.Y, part.MeshSize.Z } })\n"
            "\tmodel:Destroy()\n"
            "end\n"
            "print(HttpService:JSONEncode(out))"
        )
        return 0

    if command == "record-meshes":
        # The ids Studio resolved (the `resolve-snippet` Luau prints them as JSON): for each uploaded mesh,
        # the Model it was loaded from and the MeshPart's MeshId and MeshSize inside it. A row resolved
        # from another upload than the one the lock records -- an old resolved.json after a re-upload -- is
        # refused: it would name the previous mesh, and a regeneration that kept its bounds would pass
        # every other check while the game drew the old one.
        if len(argv) < 3:
            sys.exit("usage: upload_assets.py record-meshes <resolved.json>")
        resolved = json.loads(pathlib.Path(argv[2]).read_text())
        for item in resolved:
            record = lock["assets"].get(item["source"])
            if record is None:
                sys.exit(f"{item['source']} is not in the lock file: upload it first")
            if int(item.get("assetId") or 0) != int(record["assetId"]):
                sys.exit(
                    f"{item['source']}: resolved from model {item.get('assetId')}, the lock records "
                    f"{record['assetId']}: run resolve-snippet again in Studio"
                )
            mesh_id = str(item["meshId"]).removeprefix("rbxassetid://")
            if not mesh_id.isdigit():
                sys.exit(f"{item['source']}: {item['meshId']!r} is not a mesh id")
            native = [float(v) for v in item["native"]]
            if len(native) != 3 or min(native) <= 0:
                sys.exit(f"{item['source']}: native size {native} is not three positive numbers")
            record["meshId"] = mesh_id
            record["native"] = native
            print(f"  {item['source']}: mesh {mesh_id}, native {native}")
        save_lock(lock)
        write_blocks(lock)
        return 0

    if not user_id:
        sys.exit("no creator: set ROBLOX_USER_ID, or record it once in the lock file's creator.userId")
    key = read_key()

    if command == "quota":
        for kind, spec in KINDS.items():
            q = quota(key, user_id, spec["quota_type"])
            if q is None:
                print(f"  {spec['quota_type']}: no quota reported")
            else:
                print(
                    f"  {spec['quota_type']}: {q.get('usage', 0)} used of {q.get('capacity')} "
                    f"per {q.get('period')}, resets {q.get('usageResetTime')}"
                )
        return 0

    if command == "status":
        # Moderation, re-read: an upload is invisible or silent in a live game until Roblox approves it,
        # and the lock only knows the state at the moment of the upload.
        counts: dict[str, int] = {}
        for source, record in sorted(lock["assets"].items()):
            asset = request("GET", f"{API}/assets/v1/assets/{record['assetId']}", key)
            state = (asset.get("moderationResult") or {}).get("moderationState") or "Unknown"
            if state != record.get("moderationState"):
                record["moderationState"] = state
            counts[state] = counts.get(state, 0) + 1
            if state != "Approved":
                print(f"  {state:9s} {source} ({record['assetId']})")
        save_lock(lock)
        print("  " + ", ".join(f"{n} {state}" for state, n in sorted(counts.items())))
        return 0

    if command == "upload":
        only = [a.split("=", 1)[1] for a in argv[2:] if a.startswith("--only=")]
        audio_budget = None
        for a in argv[2:]:
            if a.startswith("--max-audio="):
                audio_budget = int(a.split("=", 1)[1])
        reupload = "--reupload" in argv[2:]
        todo = [(k, p) for k, p in plan(lock, reupload) if not only or rel(p) in only]
        lock["creator"]["userId"] = user_id
        uploaded = 0
        for kind, path in todo:
            if kind == "sound" and audio_budget is not None:
                if audio_budget <= 0:
                    print(f"  skipped (audio budget spent): {rel(path)}")
                    continue
                audio_budget -= 1
            print(f"  uploading {rel(path)}")
            try:
                asset = upload_one(key, user_id, kind, path)
            except ApiError as error:
                print(f"  FAILED {rel(path)}: {error}")
                save_lock(lock)
                write_blocks(lock)
                return 1
            lock["assets"][rel(path)] = {
                "assetId": str(asset["assetId"]),
                "assetType": asset.get("assetType"),
                "sha256": sha256(path),
                "moderationState": (asset.get("moderationResult") or {}).get("moderationState"),
                "uploadedAt": datetime.datetime.now(datetime.timezone.utc).isoformat(timespec="seconds"),
            }
            save_lock(lock)
            uploaded += 1
            print(f"    -> {asset['assetId']} {asset.get('assetType')} {lock['assets'][rel(path)]['moderationState']}")
            time.sleep(CREATE_SPACING_SECONDS)
        write_blocks(lock)
        print(f"{uploaded} uploaded")
        return 0

    sys.exit(f"unknown command {command!r}: use quota, plan, upload, status, resolve-snippet or record-meshes")


if __name__ == "__main__":
    sys.exit(main(sys.argv))
