"""The audio toolkit every generator in this directory is written with, and nothing else.

docs/JUICE_PLAN.md phase 5 allows two kinds of sound: royalty-free audio whose licence can be shown, or
sound generated by script. Everything Vellum plays is the second kind, for the same reason its textures
are: a file that came from a script is a file whose provenance is the script, and a file that came from
somewhere on the internet is a moderation case waiting to happen. So this module is a synthesiser --
oscillators, noise, envelopes, filters, a delay -- that writes 16-bit mono WAV, and every generator seeds
its own randomness so two runs write the same bytes (scripts/check.sh proves it, the way it proves the
PNGs).

Determinism is the one design constraint that shapes the code. Python's math.sin and math.exp go through
the platform's libm, and two libms can disagree in the last bit; over a million samples that is a flipped
16-bit value somewhere, and a byte-compare gate that fails on CI and passes on a laptop. So the sine here
is a polynomial, envelopes decay by multiplication, and the semitone ratios are literals. Nothing below
calls libm on a per-sample path.

Sound design vocabulary (docs/ART_BIBLE.md): the world is a page and the power is ink. Nothing here is a
laser, an engine or a synth lead. The materials are paper, brush, water, grit, air and the crack of a
quill, and the pigments are told apart by matter as much as by pitch.
"""

from __future__ import annotations

import hashlib
import struct
from pathlib import Path

MASK64 = (1 << 64) - 1

# Sample rates. Effects at 22050: a hit is a transient and its top end is what makes it a hit. Music at
# 16000: a loop is the largest file the client downloads, and a drone with sparse plucks has nothing above
# 8 kHz worth the bytes.
RATE_SFX = 22050
RATE_MUSIC = 16000

# Per-file ceiling. A loop of twenty-four seconds at 16 kHz mono is 768 KB; anything larger is a loop
# that should be shorter, not a budget that should be bigger.
MAX_BYTES = 900 * 1024

PI = 3.141592653589793
TWO_PI = 6.283185307179586

# 2 ** (k / 12) for k in 0..36, as literals, so a note is the same note on every machine.
SEMITONE = (
    1.0,
    1.0594630943592953,
    1.122462048309373,
    1.189207115002721,
    1.2599210498948732,
    1.3348398541700344,
    1.4142135623730951,
    1.4983070768766815,
    1.5874010519681994,
    1.681792830507429,
    1.7817974362806785,
    1.887748625363387,
    2.0,
    2.1189261887185906,
    2.244924096618746,
    2.378414230005442,
    2.5198420997897464,
    2.6696797083400687,
    2.8284271247461903,
    2.996614153753363,
    3.174802103936399,
    3.363585661014858,
    3.563594872561357,
    3.775497250726774,
    4.0,
    4.237852377437181,
    4.489848193237491,
    4.756828460010884,
    5.039684199579493,
    5.339359416680137,
    5.656854249492381,
    5.993228307506727,
    6.349604207872798,
    6.727171322029716,
    7.127189745122714,
    7.550994501453547,
    8.0,
)


def semitone(steps: int) -> float:
    """Frequency ratio for `steps` semitones, negative allowed, within three octaves either way. Past the
    table it raises: a clamp here once folded the top of a pentatonic onto one note, and the byte gate was
    happy because the wrong notes reproduced."""
    if abs(steps) >= len(SEMITONE):
        raise ValueError(f"{steps} semitones is outside the table (+/-{len(SEMITONE) - 1})")
    if steps >= 0:
        return SEMITONE[steps]
    return 1.0 / SEMITONE[-steps]


class Rng:
    """SplitMix64, the same eight lines tools/textures/vellum_png.py uses, for the same reason: the
    stream is ours and documented, not the interpreter's."""

    __slots__ = ("_state",)

    def __init__(self, seed: int) -> None:
        self._state = seed & MASK64

    def next_u64(self) -> int:
        self._state = (self._state + 0x9E3779B97F4A7C15) & MASK64
        z = self._state
        z = ((z ^ (z >> 30)) * 0xBF58476D1CE4E5B9) & MASK64
        z = ((z ^ (z >> 27)) * 0x94D049BB133111EB) & MASK64
        return (z ^ (z >> 31)) & MASK64

    def random(self) -> float:
        return (self.next_u64() >> 11) * (1.0 / (1 << 53))

    def uniform(self, low: float, high: float) -> float:
        return low + (high - low) * self.random()

    def signed(self) -> float:
        return self.random() * 2.0 - 1.0


# --- Arithmetic-only trigonometry -------------------------------------------------------------------


def sin(x: float) -> float:
    """sin(x) to better than 4e-6 over any argument, with no libm: range-reduce to [-pi/2, pi/2] by the
    sine's symmetries, then a Taylor polynomial. One 16-bit step is 3e-5, so the error never reaches
    the file."""
    x = x - TWO_PI * int(x / TWO_PI + (0.5 if x >= 0 else -0.5))
    if x > PI / 2:
        x = PI - x
    elif x < -PI / 2:
        x = -PI - x
    x2 = x * x
    return x * (1.0 + x2 * (-1.0 / 6.0 + x2 * (1.0 / 120.0 + x2 * (-1.0 / 5040.0 + x2 * (1.0 / 362880.0 - x2 / 39916800.0)))))


# --- Buffers ----------------------------------------------------------------------------------------


class Buf:
    """A mono float buffer at a fixed rate. Values are nominally -1..1; write() clips."""

    __slots__ = ("rate", "data")

    def __init__(self, rate: int, seconds: float) -> None:
        self.rate = rate
        self.data = [0.0] * max(1, int(rate * seconds + 0.5))

    def __len__(self) -> int:
        return len(self.data)

    def seconds(self) -> float:
        return len(self.data) / self.rate

    def add(self, other: "Buf", at: float = 0.0, gain: float = 1.0) -> "Buf":
        """Mixes `other` in, starting `at` seconds. Past the end is dropped, not extended: a layer that
        outruns its file is a design mistake worth hearing as a cut."""
        start = int(at * self.rate + 0.5)
        data = self.data
        src = other.data
        count = min(len(src), len(data) - start)
        for i in range(count):
            data[start + i] += src[i] * gain
        return self

    def scale(self, gain: float) -> "Buf":
        self.data = [v * gain for v in self.data]
        return self

    def apply(self, env: list[float]) -> "Buf":
        data = self.data
        count = min(len(env), len(data))
        for i in range(count):
            data[i] *= env[i]
        for i in range(count, len(data)):
            data[i] = 0.0
        return self


def silence(rate: int, seconds: float) -> Buf:
    return Buf(rate, seconds)


# --- Sources ----------------------------------------------------------------------------------------


def tone(rate: int, seconds: float, freq: float, freq_end: float | None = None, partials: tuple[tuple[float, float], ...] = ((1.0, 1.0),)) -> Buf:
    """A sum of sine partials (multiple, amplitude) whose fundamental glides linearly from freq to
    freq_end. Linear rather than exponential on purpose: an exponential glide needs pow() per file and
    the ear does not hold a two-hundred-millisecond sweep to a curve."""
    buf = Buf(rate, seconds)
    data = buf.data
    n = len(data)
    end = freq if freq_end is None else freq_end
    # The accumulator is never wrapped. Wrapping it at 2*pi and then multiplying by a partial's ratio
    # makes every non-integer partial jump at the wrap -- a 0.5 sub-octave came out as a half-wave
    # buzz with a mean of 0.64, and the three loops shipped with a large DC offset. sin() range-reduces
    # any argument itself, and thirty seconds at four kilohertz is under a million radians, where a
    # float still has better than a microradian.
    phase = 0.0
    step_base = TWO_PI / rate
    for i in range(n):
        f = freq + (end - freq) * (i / n)
        phase += f * step_base
        v = 0.0
        for mult, amp in partials:
            v += amp * sin(phase * mult)
        data[i] = v
    return buf


def noise(rng: Rng, rate: int, seconds: float) -> Buf:
    buf = Buf(rate, seconds)
    data = buf.data
    for i in range(len(data)):
        data[i] = rng.signed()
    return buf


def crackle(rng: Rng, rate: int, seconds: float, density: float, burst: float = 0.004, decay: float = 0.6) -> Buf:
    """Sparse bursts of noise -- embers, gravel, a dry quill. `density` is bursts per second, `burst`
    each one's length in seconds, `decay` how much quieter each burst gets over the file."""
    buf = Buf(rate, seconds)
    data = buf.data
    n = len(data)
    length = max(2, int(burst * rate))
    count = int(density * seconds)
    for _ in range(count):
        start = int(rng.random() * (n - length))
        gain = (1.0 - decay * (start / n)) * rng.uniform(0.4, 1.0)
        for j in range(length):
            data[start + j] += rng.signed() * gain * (1.0 - j / length)
    return buf


def knock(rng: Rng, rate: int, seconds: float, freq: float, q: float, tau: float) -> Buf:
    """A resonant body struck once: an impulse of noise through a narrow band, ringing down over `tau`.
    A frame drum, a woodblock, a desk -- the art bible's "percussion sèche". This is what an impact is
    made of here; a sine gliding into the sub-bass is the stock hit of every other game and is not."""
    body = bandpass(noise(rng, rate, seconds).apply(env_ad(rate, seconds, 0.0005, 0.003)), freq, q)
    return body.apply(env_ad(rate, seconds, 0.0005, tau))


def pluck(rate: int, seconds: float, freq: float, brightness: float = 0.5, rng: Rng | None = None) -> Buf:
    """Karplus-Strong: a burst of noise through a short feedback delay tuned to the pitch. The one
    synthesis that sounds like something struck rather than something switched on, which is what a
    sequence note has to be -- a quill touching the page. `brightness` is how much of the top survives
    each pass; `rng` seeds the burst, and a generator that omits it gets a fixed one."""
    buf = Buf(rate, seconds)
    data = buf.data
    period = max(2, int(rate / freq + 0.5))
    ring = [0.0] * period
    burst_rng = rng if rng is not None else Rng(0x5EED_5EED)
    for i in range(period):
        ring[i] = burst_rng.signed()
    # The loop filter has unit gain at DC, so whatever mean the burst has survives at 0.996 a period
    # while the harmonics die: a note plus a slow thump. Take the mean out before the string speaks.
    mean = sum(ring) / period
    for i in range(period):
        ring[i] -= mean
    a = 0.5 + 0.5 * brightness
    index = 0
    prev = 0.0
    for i in range(len(data)):
        v = ring[index]
        data[i] = v
        # Average with the previous pass and lose a little each time: the string's damping.
        new = (v * a + prev * (1.0 - a)) * 0.996
        ring[index] = new
        prev = v
        index += 1
        if index >= period:
            index = 0
    return buf


# --- Envelopes --------------------------------------------------------------------------------------


def env_ad(rate: int, seconds: float, attack: float, tau: float) -> list[float]:
    """Attack over `attack` seconds (a smooth rise), then an exponential decay with time constant `tau`,
    computed by one multiplication per sample."""
    n = max(1, int(rate * seconds + 0.5))
    env = [0.0] * n
    a = max(1, int(attack * rate))
    for i in range(min(a, n)):
        t = i / a
        env[i] = t * t * (3.0 - 2.0 * t)
    k = 1.0 - 1.0 / max(1.0, tau * rate)
    v = 1.0
    for i in range(a, n):
        v *= k
        env[i] = v
    return env


def env_hold(rate: int, seconds: float, attack: float, release: float) -> list[float]:
    """Rise, hold at one, release: for a body that has to last exactly a phase."""
    n = max(1, int(rate * seconds + 0.5))
    env = [1.0] * n
    a = max(1, int(attack * rate))
    r = max(1, int(release * rate))
    for i in range(min(a, n)):
        t = i / a
        env[i] = t * t * (3.0 - 2.0 * t)
    for i in range(min(r, n)):
        t = i / r
        env[n - 1 - i] = min(env[n - 1 - i], t * t * (3.0 - 2.0 * t))
    return env


# Where a swell starts. Zero would make the first third of a wind-up inaudible, and a wind-up that is
# not heard before it is seen is not a wind-up.
SWELL_FLOOR = 0.15


def env_swell(rate: int, seconds: float) -> list[float]:
    """From SWELL_FLOOR to one over the whole length, accelerating (a wind-up), and cut to zero on the
    last twenty milliseconds so the file ends without a click."""
    n = max(1, int(rate * seconds + 0.5))
    env = [0.0] * n
    tail = max(1, int(0.02 * rate))
    for i in range(n):
        t = i / n
        env[i] = SWELL_FLOOR + (1.0 - SWELL_FLOOR) * t * t
    for i in range(min(tail, n)):
        env[n - 1 - i] *= i / tail
    return env


def tremolo(rate: int, seconds: float, hz: float, depth: float, hz_end: float | None = None) -> list[float]:
    """An amplitude wobble at `hz`, gliding to `hz_end` when given: a pulse that quickens is a pulse
    whose rate glides, not a fixed one described as quickening."""
    n = max(1, int(rate * seconds + 0.5))
    env = [0.0] * n
    end = hz if hz_end is None else hz_end
    phase = 0.0
    for i in range(n):
        phase += TWO_PI * (hz + (end - hz) * (i / n)) / rate
        env[i] = 1.0 - depth * 0.5 * (1.0 + sin(phase))
    return env


# --- Filters ----------------------------------------------------------------------------------------


def lowpass(buf: Buf, cutoff: float, cutoff_end: float | None = None) -> Buf:
    """One pole, cutoff gliding linearly when an end is given. Two passes of this are a gentle slope;
    the water and wind of Indigo and Verdigris are made of exactly that."""
    data = buf.data
    n = len(data)
    end = cutoff if cutoff_end is None else cutoff_end
    y = 0.0
    k = TWO_PI / buf.rate
    for i in range(n):
        fc = cutoff + (end - cutoff) * (i / n)
        a = fc * k
        if a > 1.0:
            a = 1.0
        y += a * (data[i] - y)
        data[i] = y
    return buf


def highpass(buf: Buf, cutoff: float) -> Buf:
    data = buf.data
    y = 0.0
    a = min(1.0, cutoff * TWO_PI / buf.rate)
    for i in range(len(data)):
        y += a * (data[i] - y)
        data[i] -= y
    return buf


def bandpass(buf: Buf, centre: float, q: float, centre_end: float | None = None) -> Buf:
    """A state-variable filter's band output, the resonance set by q, the centre gliding linearly when
    an end is given. This is the brush: noise through a narrow band that moves is a stroke."""
    data = buf.data
    n = len(data)
    end = centre if centre_end is None else centre_end
    low = 0.0
    band = 0.0
    damp = 1.0 / max(0.5, q)
    # The Chamberlin form is stable while f*f + 2*f*damp < 4; 2 / (damp + 1) sits inside that for every
    # damp, where a flat clamp at 1.0 did not at the q floor and could ship a full-scale square.
    limit = 2.0 / (damp + 1.0)
    k = TWO_PI / buf.rate
    for i in range(n):
        fc = centre + (end - centre) * (i / n)
        f = fc * k
        if f > limit:
            f = limit
        high = data[i] - low - damp * band
        band += f * high
        low += f * band
        data[i] = band
    return buf


def echo(buf: Buf, delay: float, feedback: float, mix: float) -> Buf:
    """A feedback delay: the room a sound is in. Kept short for effects (a hall is a lie about where
    a fight is) and longer for the loops."""
    data = buf.data
    d = max(1, int(delay * buf.rate))
    for i in range(d, len(data)):
        data[i] += data[i - d] * feedback * mix
    return buf


def soft_clip(buf: Buf, drive: float = 1.0) -> Buf:
    """x - x^3/3, which bends a peak instead of cutting it. A hit that clips hard sounds like a broken
    speaker; one that saturates sounds heavy."""
    data = buf.data
    for i in range(len(data)):
        v = data[i] * drive
        if v > 1.5:
            v = 1.5
        elif v < -1.5:
            v = -1.5
        data[i] = v - v * v * v / 6.75
    return buf


def normalize_rms(buf: Buf, target: float, peak: float = 0.95) -> Buf:
    """Scales to an RMS of `target` (in linear units of full scale), then bends anything above `peak`
    with the soft clip rather than cutting it. Peak normalisation equalises peaks, and a tonal sub and a
    noisy tail with the same peak differ by twenty decibels to the ear; this is what lets one Volume per
    voice in SoundConfig mean the same thing for every file. sqrt is correctly rounded by IEEE 754, so
    one call per file is as deterministic as the arithmetic."""
    total = 0.0
    for v in buf.data:
        total += v * v
    rms = (total / max(1, len(buf.data))) ** 0.5
    if rms > 0.0:
        buf.scale(target / rms)
    top = 0.0
    for v in buf.data:
        a = v if v >= 0.0 else -v
        if a > top:
            top = a
    if top > peak:
        soft_clip(buf, 1.0)
        top = 0.0
        for v in buf.data:
            a = v if v >= 0.0 else -v
            if a > top:
                top = a
        if top > peak:
            buf.scale(peak / top)
    return buf


def normalize(buf: Buf, peak: float = 0.9) -> Buf:
    top = 0.0
    for v in buf.data:
        a = v if v >= 0.0 else -v
        if a > top:
            top = a
    if top > 0.0:
        buf.scale(peak / top)
    return buf


def declick(buf: Buf, seconds: float = 0.004) -> Buf:
    """Forces the first and last few milliseconds to zero. A file that starts or ends off zero clicks,
    and a click is the most recognisable artefact of a generated sound."""
    data = buf.data
    n = min(len(data), max(1, int(seconds * buf.rate)))
    for i in range(n):
        g = i / n
        data[i] *= g
        data[len(data) - 1 - i] *= g
    return buf


def loopable(buf: Buf, crossfade: float) -> Buf:
    """Makes a loop seamless by blending its tail into its head and trimming the tail: the last
    `crossfade` seconds are what the first ones become."""
    data = buf.data
    n = len(data)
    x = min(n // 2, int(crossfade * buf.rate))
    for i in range(x):
        t = i / x
        data[i] = data[i] * t + data[n - x + i] * (1.0 - t)
    buf.data = data[: n - x]
    return buf


# --- Files ------------------------------------------------------------------------------------------


def output_dir() -> Path:
    root = Path(__file__).resolve().parents[2]
    out = root / "assets" / "audio"
    out.mkdir(parents=True, exist_ok=True)
    return out


def write_wav(path: Path, buf: Buf) -> Path:
    """16-bit PCM mono. Clips at the edge rather than wrapping: an over-range sample wrapped by
    struct is the loudest possible click."""
    frames = bytearray()
    for v in buf.data:
        if v > 1.0:
            v = 1.0
        elif v < -1.0:
            v = -1.0
        frames += struct.pack("<h", int(v * 32767.0))
    data_size = len(frames)
    header = b"RIFF" + struct.pack("<I", 36 + data_size) + b"WAVE"
    fmt = b"fmt " + struct.pack("<IHHIIHH", 16, 1, 1, buf.rate, buf.rate * 2, 2, 16)
    path.write_bytes(header + fmt + b"data" + struct.pack("<I", data_size) + bytes(frames))
    return path


def read_wav_info(path: Path) -> tuple[int, int, int, float]:
    """(rate, channels, bits, seconds), read from the file's own header so verification measures what
    was written and not what the generator meant."""
    head = path.read_bytes()[:44]
    if head[:4] != b"RIFF" or head[8:12] != b"WAVE":
        raise ValueError(f"{path} is not a WAV")
    channels, rate = struct.unpack("<HI", head[22:28])
    bits = struct.unpack("<H", head[34:36])[0]
    data_size = struct.unpack("<I", head[40:44])[0]
    seconds = data_size / (rate * channels * (bits // 8))
    return rate, channels, bits, seconds


def report(paths: list[Path]) -> int:
    over = 0
    for path in paths:
        rate, channels, bits, seconds = read_wav_info(path)
        size = path.stat().st_size
        digest = hashlib.sha256(path.read_bytes()).hexdigest()[:16]
        flag = ""
        if size > MAX_BYTES:
            over += 1
            flag = f"  OVER BUDGET ({MAX_BYTES} bytes)"
        print(f"{path.name:<28} {rate:>5} Hz {channels}ch {bits}b {seconds:>6.2f}s {size:>8} bytes  {digest}{flag}")
    return over
